### PR TITLE
Brief introduction about me and what am I doing.

### PR DESCRIPTION
**Pull request by kpl-grwl**

### CODE REVIEW

**Comment by audrism** [comment]
Hi Kapil, 
You closed the pull request, so I can not merge it. Could you submit it again?

Thank you, Audris

**Comment by audrism** [comment]
Hi Kapil, 

It turns out I can reopen it myself. Is that OK if I merge it?

Thank you, 
 Audris

**Comment by kpl-grwl** [comment]
Yes please, I am new to github so probably still looking around. Also, I
wanted to ask is it necessary to install Virtual Machine if you have a Mac
or can I just install the python packages, ipython, R, java and mathjax?

Thanks,
Kapil

**Comment by audrism** [comment]
No, if it works for the mac no need to bother with VM. 

The only advantage of trying VM is that you would get a little practice of being able to deploy your application to the cloud.

**Comment by kpl-grwl** [comment]
Dear Dr. Mockus,

I wont be able to attend your class today as I have fallen sick. Please let
me know if there is something that I need to do.

Thanks,
Kapil

**Comment by audrism** [comment]
Kapil, 

Try to get well first!
I have recorded the class, so you are welcome to watch the video (i'll put a link
at the top of the syllabus (fdac/syllabus) as soon as the website hosting the videos will come back up). 

Once you feel better, please try to go over Assignment1 and submit a pull request.
We will be discussing it on Monday and, if the recording cooperates, I will try to 
record the Monday's discussion as well. If you have questions or need help, please let me know.

**Comment by kpl-grwl** [comment]
Dear Dr. Mockus,

I just checked the assignment 1 before creating a pull request. It seems
gutenburg.org is down giving error 403. I though have coded for the extra
credit but I am unable to get the results. Can I go ahead and explain what
I wanted to do and later update the analysis once the site is up back again?

Regards,
Kapil

**Pull request merged**
